import type {Metadata} from "next";
import {Inter, Open_Sans} from "next/font/google";
import "./globals.css";

const inter = Inter({subsets: ["latin"]});
const openSans = Open_Sans({subsets: ["latin"], display: "swap"});

export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={openSans.className}>
        <main className='min-h-screen scroll-smooth'>{children}</main>
      </body>
    </html>
  );
}
